# Generated by Django 4.2 on 2023-04-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_alter_mylogindetials_app_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylogindetials',
            name='app_category',
            field=models.CharField(choices=[('Entertainment', 'Entertainment'), ('Eductional', 'Eductional'), ('Lifestyle', 'Lifestyle'), ('food', 'food'), ('common', 'common'), ('productivity', 'productivity')], default='App category', max_length=255),
        ),
    ]
