# Generated by Django 4.2 on 2023-04-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_alter_mylogindetials_app_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylogindetials',
            name='app_category',
            field=models.CharField(choices=[('Entertainment', 'Entertainment'), ('Eductional', 'Eductional'), ('Lifestyle', 'Lifestyle'), ('food', 'food'), ('common', 'common'), ('productivity', 'productivity')], default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='mylogindetials',
            name='sub_category',
            field=models.CharField(choices=[('social Media', 'social Media'), ('games', 'games'), ('coding', 'coding'), ('kids', 'kids'), ('clothing', 'clothing'), ('fashion', 'fashion'), ('local', 'local'), ('allindia', 'allindia'), ('common', 'common'), ('utility', 'utility'), ('finance', 'finance'), ('music', 'music'), ('travel', 'travel')], default=1, max_length=255),
        ),
    ]
