# Generated by Django 4.2 on 2023-04-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_alter_mylogindetials_app_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='userLoginDetials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='subCategory',
        ),
    ]
