# Generated by Django 4.2 on 2023-04-16 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_userlogindetials_delete_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userLoginDetials',
        ),
    ]
