# Generated by Django 4.2 on 2023-04-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0008_myuserdetials'),
    ]

    operations = [
        migrations.CreateModel(
            name='myscreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(blank=True, upload_to='screenshot/')),
            ],
        ),
    ]
