# Generated by Django 4.2 on 2023-04-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0009_myscreenshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myscreenshot',
            old_name='screenshot',
            new_name='img',
        ),
    ]
