# Generated by Django 4.2 on 2023-04-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0010_rename_screenshot_myscreenshot_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myscreenshot',
            name='img',
        ),
        migrations.AddField(
            model_name='myscreenshot',
            name='image',
            field=models.ImageField(blank=True, upload_to='app_images/'),
        ),
    ]
