# Generated by Django 4.2 on 2023-04-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0011_remove_myscreenshot_img_myscreenshot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myscreenshot',
            name='image',
            field=models.ImageField(upload_to='screenshot/'),
        ),
    ]
