# Generated by Django 4.2 on 2023-04-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0012_alter_myscreenshot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylogindetials',
            name='image',
            field=models.ImageField(upload_to='app_images/'),
        ),
    ]
